library(ggplot2)
x <- c(1, 2, 3, 4, 5)
y <- c(3, 5, 2, 8, 7)
data <- data.frame(x = x, y = y)
ggplot(data, aes(x = x, y = y)) 
  geom_line(color = "blue") 
  geom_point(color = "red") 
  ggtitle("My Line Plot") 
  xlab("X Axis Label") 
  ylab("Y Axis Label")
